#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" showgrid - just a stupid little program that reads (x, y)
cordinates from stdin and makes a grid of it.
"""

import sys

cells = {}
min_x, min_y, max_x, max_y = None, None, None, None
for row in sys.stdin:
    x, y = row.split(' ')
    x, y = int(x), int(y)
    cells[y, x] = 1
    min_x = min(min_x, x) if min_x is not None else x
    min_y = min(min_y, y) if min_y is not None else y
    max_x = max(max_x, x) if max_x is not None else x
    max_y = max(max_y, y) if max_y is not None else y

for y in range(min_y, max_y + 1):
    for x in range(min_x, max_x + 1):
        if (y, x) in cells:
            sys.stdout.write('x')
        else:
            sys.stdout.write(' ')
    sys.stdout.write('\n')
    sys.stdout.flush()
